In [2]:
""" Chapter 6: Gated Recurrent Units (GRUs)
- Assess the drawback of simple RNNs
- Describe the architecture of GRUs
- Perfor setntiment analysis usiing GRUs
- Apply GRUs for text generation 
"""
import numpy as np 
# Write a sigmoid funciton to be used later in the program 
def sigmoid(x):
    return 1/ (1 + np.exp(-x))

n_x = 5 # Dimensionality of input vector 
n_h = 3 # Number of hidden units 
# Define an input at time 't'  having a dimensionality of n_x
x_t = np.random.randn(n_x,1)
#Define W_z, U_z and h_prev (last time step activation)
W_z  = np.random.randn(n_h, n_x) # n_h = 3, n_x = 5
U_z = np.random.randn(n_h, n_h)
h_prev = np.random.randn(n_h, 1)
print("x_t", "\n",x_t)
print("h_prev", "\n",h_prev)
print("W_z", "\n",W_z)
print("U_z", "\n",U_z)

# Calculate expression for update gate
z_t = sigmoid(np.matmul(W_z, x_t) + np.matmul(U_z, h_prev))
print("z_t", "\n",z_t)

x_t 
 [[ 0.027505  ]
 [-0.20436048]
 [-0.73118598]
 [-0.75645298]
 [-2.89257329]]
h_prev 
 [[1.96865023]
 [1.08601353]
 [1.33766752]]
W_z 
 [[ 0.11351264 -1.15629545  0.68240702 -0.02559766 -0.7054325 ]
 [ 1.68878441  1.33677135 -1.85687492 -0.65589493 -2.04655839]
 [-1.01134307  0.76285632  1.33073624 -1.438581    0.15244445]]
U_z 
 [[ 0.40402939 -0.0152215   0.24598296]
 [ 0.8648696   0.71199284  0.19960275]
 [ 0.94424046  0.5013119  -0.32565198]]
z_t 
 [[0.9482523 ]
 [0.99996602]
 [0.81126157]]


In [3]:
# Define W_r, U_r 
W_r = np.random.randn(n_h, n_x) # n_h = 3, n_x = 5
U_r = np.random.randn(n_h, n_h) # n_h = 3
# calculate  expression for update gate
r_t = sigmoid(np.matmul(W_r, x_t) + np.matmul(U_r, h_prev))
print("W_r", "\n",W_r)
print("U_r", "\n",U_r)
print("r_t", "\n",r_t)
# r_t = r_t > 0.5
# print("r_t", "\n",r_t)

"""note that the values of r_t may not be particularly close to either 0 or 1, but in well-trained network, 
they are expected to be close to 0 or 1 """

W_r 
 [[-1.65964205  0.87294066 -0.8053601  -1.27523796 -0.62194868]
 [-0.96112401  0.30804179  0.49354157  0.95760112  1.06462417]
 [-0.496121   -1.52340271 -0.04564732  2.13781999 -0.56781337]]
U_r 
 [[ 0.81352377 -1.53698535 -0.29627467]
 [-1.20958334 -0.87335414  1.01818801]
 [-0.68290151  1.25801294 -0.54141143]]
r_t 
 [[0.93490241]
 [0.0019816 ]
 [0.41433625]]


'note that the values of r_t may not be particularly close to either 0 or 1, but in well-trained network, \nthey are expected to be close to 0 or 1 '

In [4]:
# The candidate activation function 
#Define W,U 
W = np.random.randn(n_h,n_x) # n_h = 3, n_x = 5
U = np.random.randn(n_h, n_h)
# calculate h_candidate
h_candidate =  np.tanh(np.matmul(W, x_t) + np.matmul(U, np.multiply(r_t,h_prev)))
print("W", "\n",W)
print("U", "\n",U)
print("h_candidate", "\n",h_candidate)

W 
 [[-0.19528449 -0.2396007   0.1186256   0.76466493  0.13075172]
 [-1.3848266  -0.66722835  2.46545262  1.40780109  0.03723913]
 [ 1.58429712 -1.2944336  -0.04179853  1.47930436 -0.06817499]]
U 
 [[-0.86160778  1.73257474 -0.08230005]
 [ 1.5532152  -1.53528431  0.89440347]
 [ 0.75083364 -0.47371584  0.88435867]]
h_candidate 
 [[-0.98961066]
 [ 0.44143266]
 [ 0.85857134]]
